---
- name: Install EPEL
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: installed

- name: Install collectd and plugins
  package:
    name: "{{ item }}"
    state: installed
  with_items:
  - collectd
  - collectd-lvm

- name: Allow collectd to network connect
  seboolean:
    name: collectd_tcp_network_connect
    state: yes
    persistent: yes

# This is to workaround the selinux policy not supporting the collectd-lvm
# plugin
- name: Set the collectd_t selinux domain to permissive
  selinux_permissive:
    name: collectd_t
    permissive: true

- name: Copy the collectd config
  template:
    src: collectd.conf
    dest: /etc/collectd.conf
  notify: restart collectd

- name: Enable and start the collectd service
  service:
    name: collectd
    enabled: yes
    state: started
