---
- hosts: localhost
  gather_facts: no
  become: no
  vars_files:
  - vars.defaults.yml
  vars:
    demo_route_53_subdomain: "{{ cluster_id }}.{{ env_id }}.{{ demo_route_53_zone }}"
    env_cluster_hosts: "{{ groups['tag_environment_' ~ env_id]
                           | intersect(groups['tag_clusterid_' ~ cluster_id]) }}"
    master_hosts: "{{ groups['tag_environment_' ~ env_id]
                      | intersect(groups['tag_clusterid_' ~ cluster_id]
                                  | intersect( groups['tag_host-type_master'])) }}"
    node_hosts: "{{ groups['tag_environment_' ~ env_id]
                    | intersect(groups['tag_clusterid_' ~ cluster_id]
                                | intersect(groups['tag_host-type_node'])) }}"
  tasks:
  - include: tasks/group_setup.yml
  - debug: var=groups

#- include: openshift-ansible-contrib/playbooks/provisioning/aws/cloudformation/ops_mirror.yml

#- include: openshift-ansible/playbooks/byo/openshift-cluster/config.yml
