---
- hosts: localhost
  gather_facts: no
  become: no
  connection: local
  tags:
  - always
  vars:
    env_cluster_hosts: "{{ groups['tag_environment_' ~ env_id]
                           | intersect(groups['tag_clusterid_' ~ cluster_id]) }}"
    master_hosts: "{{ groups['tag_environment_' ~ env_id]
                      | intersect(groups['tag_clusterid_' ~ cluster_id]
                                  | intersect( groups['tag_host-type_master'])) }}"
    node_hosts: "{{ groups['tag_environment_' ~ env_id]
                    | intersect(groups['tag_clusterid_' ~ cluster_id]
                                | intersect(groups['tag_sub-host_type_compute'])) }}"
    infra_hosts: "{{ groups['tag_environment_' ~ env_id]
                     | intersect(groups['tag_clusterid_' ~ cluster_id]
                                 | intersect(groups['tag_sub-host_type_infra'])) }}"
  tasks:
  - include: tasks/group_setup.yml

- hosts: masters[0]
  tags:
  - post
  roles:
  - gogs
  - pipeline
  - che
  tasks:
  - name: Create the new imagestreams
    shell: >
      echo {{ lookup('file', item) | from_json | to_json | quote }} | oc create -n openshift -f -
    register: create_is
    failed_when: "create_is.rc == 1 and 'already exists' not in create_is.stderr"
    changed_when: create_is.rc ==0
    with_fileglob:
    - files/imagestreams/*.json

- hosts: nodes
  tags:
  - post
  tasks:
  - name: Pre-pull docker images
    command: "docker pull {{ item }}"
    with_items:
    - jboss-eap-7/eap70-openshift
    - rhscl/nodejs-4-rhel7
