---
- hosts: localhost
  gather_facts: no
  become: no
  vars_files:
  - vars.defaults.yml
  vars:
    demo_route_53_subdomain: "{{ cluster_id }}.{{ env_id }}.{{ demo_route_53_zone }}"
  tasks:
  - include: tasks/create_vpc.yml
    when: demo_create_vpc | default(False) | bool

  - include: tasks/create_sgs.yml
    when: demo_create_sgs | default(False) | bool

  - include: tasks/create_hosts.yml
    when: demo_create_hosts | default(False) | bool


#- include: openshift-ansible-contrib/playbooks/provisioning/aws/cloudformation/group_setup.yml

#- hosts: localhost
#  gather_facts: no
#  become: no
#  tasks:
#  - debug: var=groups

#- include: openshift-ansible-contrib/playbooks/provisioning/aws/cloudformation/ops_mirror.yml

#- include: openshift-ansible/playbooks/byo/openshift-cluster/config.yml
