---
- hosts: localhost
  gather_facts: no
  become: no
  connection: local
  vars_files:
  - vars.provisioning.yml
  tasks:
  - include: tasks/teardown_hosts.yml
    when: demo_create_hosts | default(False) | bool

  - include: tasks/teardown_sgs.yml
    when: demo_create_sgs | default(False) | bool

  - include: tasks/teardown_vpc.yml
    when: demo_create_vpc | default(False) | bool
