- name: wait for ssh
  wait_for: "port=22 host={{ item }}"
  with_items: "{{ env_cluster_hosts }}"

- set_fact:
    openshift_hosted_registry_storage_s3_bucket: "{{ demo_registry_storage_s3_bucket }}"

- name: Add masters to requisite groups
  add_host:
    name: "{{ item }}"
    groups: masters, etcd, nodes, cluster_hosts, OSEv3, cluster_{{ env_id }}_{{ cluster_id }}
    openshift_node_labels:
      node_type: master
      region: "{{ hostvars[item].ec2_region }}"
      zone: "{{ hostvars[item].ec2_placement }}"
    openshift_hosted_registry_storage_s3_bucket: "{{ demo_registry_storage_s3_bucket }}"
  with_items: "{{ master_hosts }}"
  changed_when: false

- name: Add nodes to requisite groups
  add_host:
    name: "{{ item }}"
    groups: nodes, cluster_hosts, OSEv3, cluster_{{ env_id }}_{{ cluster_id }}
    openshift_node_labels:
      node_type: compute
      region: "{{ hostvars[item].ec2_region }}"
      zone: "{{ hostvars[item].ec2_placement }}"
    openshift_hosted_registry_storage_s3_bucket: "{{ demo_registry_storage_s3_bucket }}"
  with_items: "{{ node_hosts }}"
  changed_when: false

- name: Add infra nodes to requisite groups
  add_host:
    name: "{{ item }}"
    groups: nodes, cluster_hosts, OSEv3, cluster_{{ env_id }}_{{ cluster_id }}
    openshift_node_labels:
      node_type: infra
      region: "{{ hostvars[item].ec2_region }}"
      zone: "{{ hostvars[item].ec2_placement }}"
    openshift_hosted_registry_storage_s3_bucket: "{{ demo_registry_storage_s3_bucket }}"
  with_items: "{{ infra_hosts }}"
  changed_when: false
