apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: jenkins
      keynote: "2016"
      template: jenkins-s2i
    name: jenkins
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: jenkins
      keynote: "2016"
      template: jenkins-s2i
    name: jenkins
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: {{ env_id }}
        uri: https://github.com/Red-Hat-Middleware-Keynote/openshift-jenkins-s2i-config.git
      secrets: null
      sourceSecret:
        name: git-secret
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: jenkins-1-rhel:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: {{ demo_pipeline_github_trigger_secret }}
      type: GitHub
    - generic:
        secret: {{ demo_pipeline_generic_trigger_secret }}
      type: Generic
    - type: ConfigChange
