---
- name: Create the ui project
  command: oadm new-project ui-proxy
  register: ui_project
  failed_when: "{{ ui_project.rc == 1 and 'already exists' not in ui_project.stderr }}"
  changed_when: "{{ ui_project.rc == 0 }}"

- name: Create the ui-proxy template
  shell: >
    echo {{ lookup('file', 'ui_proxy.yml') | from_yaml | to_json | quote }} |  oc create -n ui-proxy -f -
  register: ui_template
  failed_when: "{{ ui_template.rc == 1 and 'already exists' not in ui_template.stderr }}"
  changed_when: "{{ ui_template.rc == 0 }}"

  # TODO set APPLICATION_DOMAIN
- name: Create the ui-proxy app
  command: >
    oc new-app -n ui-proxy --template=ui-proxy-template --param="REPLICAS={{ demo_ui_replicas }},S3_BUCKET_TO_PROXY={{ demo_ui_s3_bucket }},HTPASSWD_CONTENTS={{ demo_ui_htpasswd_contents }},NAME=ui-proxy"
