---
- name: Create the projects
  command: oadm new-project "{{ item }}"
  with_items: "{{ demo_projects | union(demo_pipeline_projects) }}"
  register: create_projects
  failed_when: "{{ create_projects.rc == 1 and 'already exists' not in create_projects.stderr }}"
  changed_when: "{{ create_projects.rc == 0 }}"

- name: Add admin users to projects
  command: oc policy add-role-to-user -n {{ item.0.item }} admin {{ item.1 }}
  with_nested:
  - "{{ create_projects.results }}"
  - "{{ demo_project_admin }}"

- name: Add view users to projects
  command: oc policy add-role-to-user -n {{ item.0.item }} view {{ item.1 }}
  with_nested:
  - "{{ create_projects.results }}"
  - "{{ demo_project_view }}"

- name: Create the git secret
  command: oc secrets new-basicauth git-secret --username={{ demo_github_user }} --password={{ demo_github_password }} -n {{ item }}
  with_items:
  - "{{ demo_projects }}"
  register: git_secret
  failed_when: "{{ git_secret.rc == 1 and 'already exists' not in git_secret.stderr }}"
  changed_when: "{{ git_secret.rc == 0 }}"

- name: Add the git secret to the builder service account
  command: oc secrets add serviceaccount/builder secrets/git-secret -n {{ item }}
  with_items: "{{ demo_projects }}"
  register: add_git_secret
